version: '3.7'
services:
  tio-notifier-cdp-tag:
    image: tio-notifier-cdp-tag
    restart: always
    build: .
    environment:
      TZ: "America/Sao_Paulo"
    ports:
      - 8080:8080
    
    
    command: java -jar /app/app.jar
    
